web:
  address: '0.0.0.0'
  port: 8080
  autoreload: on
  debug: on

database:
  address: '127.0.0.1'
  port: 27017

email:
  address: '127.0.0.1'
  port: 25
  login: off
  user: ''
  password: ''

logging:
  version: 1
  disable_existing_loggers: true
  formatters:
    default:
      format: '[%(asctime)s][%(levelname)s]: %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    file:
      class: logging.handlers.RotatingFileHandler
      filename: logs/server.log
      formatter: default
      level: NOTSET
      maxBytes: 1048576
      backupCount: 0
    console:
      class: logging.StreamHandler
      formatter: default
      level: NOTSET
  root:
    level: INFO
    handlers: [file, console]
  loggers:
    tornado.access:
      level: INFO
      handlers: [file, console]
      qualname: tornado.access
      propagate: false
    tornado.application:
      level: INFO
      handlers: [file, console]
      qualname: tornado.application
      propagate: false
    tornado.general:
      level: INFO
      handlers: [file, console]
      qualname: tornado.general
      propagate: false